### ISSUE TITLE
INFORMACIÓN DE UN PAR DE ACTIVOS

### ISSUE THREAD

**Issue by Andres-Goicoechea-Enrique** [lkristianl/CryptoManager#35]
Con esta feature el usuario podrá realizar ver el último precio de venta y de compra, el libro de órdenes, la gráfica, el volumen en las últimas 24 horas, el precio de apertura, cierre, máximo, mínimo y las operaciones recientes de un determinado par de activos, como por ejemplo BTC/USD o BTC/EUR, en los distintos exchanges que tenga vinculados con su cuenta en la aplicación web.

Prioridad: M

Historias de usuario relacionadas con esta feature:
- [ ] #38 Mostrar último precio venta y compra
- [ ] #43 Mostrar el libro de órdenes
- [ ] #49 Mostrar gráfica
- [ ] #57 Mostrar volumen en las últimas 24 horas
- [ ] #63 Mostrar datos OHLC(Apertura, Máximo, Mínimo, Cierre)
- [ ] #69 Mostar operaciones recientes
