### ISSUE TITLE
Datos privados del usuario

### ISSUE THREAD

**Issue by lkristianl** [lkristianl/CryptoManager#42]
Con esta feature el usuario podrá ver su balance total de la cuenta, el balance para operar, las órdenes abiertas y cerradas, información de las órdenes y el historial de operaciones de los distintos exchanges que tenga vinculados con su cuenta en la aplicación web.

Prioridad: H

Historias de usuario relacionadas con esta feature:
- [ ] #45 Mostrar el balance de la cuenta
- [ ] #48 Mostrar el balance para operar
- [ ] #50 Ordenes abiertas
- [ ] #51 Ordenes cerradas
- [ ] #52 Mostrar información de las órdenes
- [ ] #56 Mostrar historial de operaciones
