### ISSUE TITLE
[Datos privados del usuario] Mostrar el balance de la cuenta

### ISSUE THREAD

**Issue by lkristianl** [lkristianl/CryptoManager#45]
Como usuario quiero poder ver el balance total de criptomonedas y  en una moneda FIAT que tengo entre todas mis carteras de exchanges. Adicionalmente, quiero poder ver el balance total por cada exchange asociado a mi cuenta de la aplicación web.

Prioridad: H

- [ ] #61 Mostrar balance global de usuario
- [ ] #62 Mostrar balance de la cartera de Kraken del usuario
- [ ] #64 Mostrar balance de la cartera de Binance del usuario
- [ ]  #66 Mostrar balance de otra cartera del usuario
