### ISSUE TITLE
[Datos privados del usuario] Mostrar el balance para operar

### ISSUE THREAD

**Issue by lkristianl** [lkristianl/CryptoManager#48]
Como usuario quiero poder ver el balance en una moneda FIAT que tengo disponible en un exchange para comprar/vender criptomonedas.

Prioridad: M

- [ ] #74 Mostrar balance para operar de la cartera de Kraken del usuario
- [ ] #75 Mostrar balance para operar de la cartera de Binance del usuario
- [ ] #73 Mostrar balance para operar de otra cartera del usuario
