### ISSUE TITLE
[Depósitos de usario] Depositar FIAT

### ISSUE THREAD

**Issue by lkristianl** [lkristianl/CryptoManager#5]
Como usuario quiero poder depositar monedas FIAT desde mi cuenta bancaria a una cuenta de un exchange para poder realizar compra y venta de criptomonedas.

Prioridad: H

- [ ] #6 Añadir soporte para el exchange de Kraken 
- [ ] #7 Añadir soporte para el exchange de Binance
- [ ] #8 Añadir soporte para mas exchange
