### ISSUE TITLE
[Datos privados del usuario] Mostrar información de las órdenes

### ISSUE THREAD

**Issue by lkristianl** [lkristianl/CryptoManager#52]
Como usuario quiero poder ver la información (precio de compra/venta, cantidad de la criptomoneda a comprar/vender, fecha de emisión, estado de la orden, etc) asociada a cada orden que haya realizado en un exchange.

Prioridad: M

- [ ] #89 Añadir soporte para el exchange de Kraken
- [ ] #90 Añadir soporte para el exchange de Binance
- [ ] #88 Añadir soporte para mas exchange
