### ISSUE TITLE
[INFORMACIÓN DE UN PAR DE ACTIVOS] Mostrar datos OHLC(Apertura, Máximo, Mínimo, Cierre)

### ISSUE THREAD

**Issue by Andres-Goicoechea-Enrique** [lkristianl/CryptoManager#63]
Como usuario quiero poder ver el precio de apertura, el precio máximo, el precio mínimo y el precio de cierre de un par de activos en las últimas 24 horas.

Prioridad: L

- [ ] #65 Añadir soporte para el exchange de Kraken
- [ ] #67 Añadir soporte para el exchange de Binance
- [ ] #68 Añadir soporte para más exchanges
- [ ] #136 Opciones de visualización para cualquier exchange
