### ISSUE TITLE
RETIROS DE USUARIO

### ISSUE THREAD

**Issue by Andres-Goicoechea-Enrique** [lkristianl/CryptoManager#9]
Con esta feature el usuario podrá realizar retiros de monedas FIAT, obtener información de los retiros, mostrar el estado de los retiros recientes y solicitar la cancelación de un retiro en los distintos exchanges que tenga vinculados con su cuenta en la aplicación web.

Prioridad: M

Historias de usuario relacionadas con esta feature:
- [ ] #10 Retirar FIAT
- [ ] #14 Obtener información de los retiros
- [ ] #19 Mostrar estado de retiros recientes
- [ ] #28 Solicitar la cancelación de un retiro
